### ISSUE TITLE
Type or namespace 'LTSeq' could not be found

### ISSUE THREAD

**Issue by RuudvanReenen** [dentedpixel/LeanTween#173]
After updating to 2.51, I'm getting this error:

Assets\Plugins\LeanTween.cs(1057,19): error CS0246: The type or namespace name 'LTSeq' could not be found (are you missing a using directive or an assembly reference?)

Unity 2020.3.26f1 on Windows 10 x64, building for Android.

**Comment by basisbit** [comment]
This project has been dead since 2018. the developer does not respond here any more. You might want to switch to another tween tool.

**Comment by RuudvanReenen** [comment]
Ok, thanks for the heads-up!
Odd though, the plugin has been updated in December: https://assetstore.unity.com/packages/tools/animation/leantween-3595#releases

**Comment by breadnone** [comment]
Yes, apparently he just updated to fix issues with Unity 2021.. so there's a hope!
